from .constants import (CLASS_NAME_PIPELINES, FIELDS, FORMAT_FILE,
                        NAME_FILE_PEP, NAME_FOLDER_SAVING_FILES,
                        MODULE_NAME_SPIDERS, PROJECT_NAME)

BOT_NAME = PROJECT_NAME

SPIDER_MODULES = [MODULE_NAME_SPIDERS]
NEWSPIDER_MODULE = MODULE_NAME_SPIDERS

ROBOTSTXT_OBEY = True

FEEDS = {
    f'{NAME_FOLDER_SAVING_FILES}/{NAME_FILE_PEP}_%(time)s.{FORMAT_FILE}': {
        'format': FORMAT_FILE,
        'fields': FIELDS,
        'overwrite': True
    },
}
ITEM_PIPELINES = {
    CLASS_NAME_PIPELINES: 300,
}
